services:

  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    hostname: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://127.0.0.1:8099 # change this to your prod url with https
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=USERPW1
      - DB_DATABASE=bookstackapp
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/bookstack/config:/config
    restart: unless-stopped
    ports:
      - 8099:80
    expose:
      - 80
    depends_on:
      - bookstack_db
    #networks:
    #  - proxy

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    hostname: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ROOTPW
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=USERPW1
    expose:
      - 3306
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/bookstack/mariadb-config:/config
    restart: unless-stopped
    #networks:
    #  - proxy

#networks:
#  proxy:
#    external: true  